### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by jonheller1** [oracle-developer/dla#1]
Can you add a license to DLA to make it clear how we can use the code?  I see some of your code says things like "free to use".  It would be helpful if this was made explicit with a specific license.

I'm using DLA to make a more generic method4 implementation at https://github.com/jonheller1/method4 .  I hope to some day incorporate that in larger open source projects but it would require a more clear license.  And I plan to push back some changes to DLA some day; there are so many weird cases with the Any Types that I've run into.

Thanks for creating this excellent program!

**Comment by oracle-developer** [comment]
Added MIT License.
